#!/bin/bash
# rm terraform.tfstate*
terraform init
if [ $? -ne 0 ]; then
  echo "Terraform initialization failed."
  exit 1
fi
echo "Terraform initialization successful."

terraform validate
if [ $? -ne 0 ]; then
  echo "Terraform validation failed."
  exit 1
fi
echo "Terraform validation successful."

while true; do
  terraform apply -auto-approve
  if [ $? -eq 0 ]; then
    echo "Terraform apply successful."
    break
  else
    echo "Terraform apply failed. Retrying in 1 second..."
    sleep 1
  fi
done