apiVersion: v1
kind: ServiceAccount
metadata:
  name: uplion-admin-panel-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: uplion-admin-panel-clusterrole
rules:
- apiGroups: ["model.youxam.com"]
  resources: ["aimodels"]
  verbs: ["list", "create", "get", "update", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: uplion-admin-panel-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: uplion-admin-panel-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: uplion-admin-panel-clusterrole
  apiGroup: rbac.authorization.k8s.io
