apiVersion: v1
kind: Service
metadata:
  name: uplion-admin-panel-service
spec:
  selector:
    app: uplion-admin-panel
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: uplion-admin-panel-nodeport-service
spec:
  selector:
    app: uplion-admin-panel
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30008
  type: NodePort

