apiVersion: v1
kind: Namespace
metadata:
  name: aimodel-go
---
apiVersion: model.youxam.com/v1alpha1
kind: AIModel
metadata:
  labels:
    app.kubernetes.io/name: aimodel
    app.kubernetes.io/instance: aimodel-sample
    app.kubernetes.io/part-of: aimodel-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: aimodel-operator
  name: aimodel-go-sample
  namespace: aimodel-go
spec:
  type: local
  model: static
  replicas: 3
  image: yiwencai/uplion-worker-node-go:latest

