apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pg-namespace.yml
  - pg-configmap.yaml
  - psql-pv.yaml
  - psql-claim.yaml
  - ps-deployment.yaml
  - ps-service.yaml


namespace: postgresql
